# Global Justfile
# Coordinates the variety of useful scripts for
# managing a Workspace of projects.

# config := "~/.config/just"

# Standard Module
mod std '~/.config/just/std.just'
# Tools Module
mod tools '~/.config/just/tools.just'
# GIT Module
mod git '~/.config/just/git.just'
# PKL Module
mod pkl '~/.config/just/pkl.just'
# Boot Module
mod boot '~/.config/just/boot.just'

# About Constellation Tools
_default:
    @echo '{{ style("warning") }}Global Commands{{ NORMAL }}'
    @echo @{{source_file()}}
    @echo ""
    @just -f {{source_file()}} --list

set unstable

bosh := which("bosh")
[private]
@test:
    echo "bosh: '{{bosh}}'"
    echo "just: '{{which("just")}}'"
    echo "brew: '{{which("brew")}}'"
