# Global Just Commands
default:
    @echo "Global Commands"
    @echo "Justfile @" $PWD
    @echo ""
    @just --list

# Common Commands
time:
	@echo `date`

# SECRETS
[private]
secret:
    @echo Handle secrets here
